//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.cartItems = new HashSet<cartItems>();
        }

        [Display(Name = "Product ID")]
        public string prodID { get; set; }

        [Display(Name = "Product Name")]
        public string prodName { get; set; }

        [Display(Name = "Product Price")]
        public int prodPrice { get; set; }

        [Display(Name = "Product Description")]
        public string prodDesc { get; set; }

        [Display(Name = "Product Amount")]
        public long prodAmount { get; set; }

        [Display(Name = "Product Link")]
        public string prodLink { get; set; }
        public string prodRevImg { get; set; }
        public string prodImg1 { get; set; }
        public string prodImg2 { get; set; }
        public string prodImg3 { get; set; }
        public string prodImg4 { get; set; }
        public int catID { get; set; }
        public int matID { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual materials materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cartItems> cartItems { get; set; }
    }
}
