//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {
        [Key, Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "UUID")]
        public int userID { get; set; }

        [Required(ErrorMessage = "Please input your full name")]
        [StringLength(50, MinimumLength = 5)]
        [DataType(DataType.Text)]
        [Display(Name = "Full name")]
        public string userFullName { get; set; }

        [Required(ErrorMessage = "Please input your username")]
        [StringLength(30, MinimumLength = 8)]
        [DataType(DataType.Text)]
        [Display(Name = "Username")]
        public string username { get; set; }

        [Required(ErrorMessage = "Please input your email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Your email is not valid!")]
        [Display(Name = "Email")]
        public string userEmail { get; set; }

        [Required(ErrorMessage = "Please input your phone number")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Your phone number is not valid!")]
        [Display(Name = "Phone number")]
        public string userPhone { get; set; }

        [Required(ErrorMessage = "Please input your password")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string userPassword { get; set; }

        [Required(ErrorMessage = "Please choose your gender")]
        [Display(Name = "Gender")]
        public int userGender { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Avatar")]
        public string userAvatar { get; set; }

        //[Required(ErrorMessage = "Please input your address")]
        [DataType(DataType.Text)]
        [Display(Name = "Address")]
        public string userAddress { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Bio")]
        public string userBio { get; set; }

        [NotMapped]
        [DataType(DataType.Text)]
        [Display(Name = "Account")]
        public string userAccount { get; set; }

        [NotMapped]
        [Display(Name = "Retype password")]
        [Compare("userPassword", ErrorMessage = "Password does not match")]
        public string comfirmPassword { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Role")]
        public int roleID { get; set; }
    }
}
